default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: personal_blog_development

test:
  <<: *default
  database: personal_blog_test

production:
  <<: *default
  database: personal_blog_production
  username: personal_blog
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
